name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
  
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Testing SCU
      uses : http://estore.merge.com/mergecom3/download-thanks.aspx?productId=b1534ecc-1e57-480c-b5ca-5681b30e996f
